### ISSUE TITLE
Error: Extension host terminated unexpectedly

### ISSUE THREAD

**Issue by SebastianKristof** [jaime-olivares/yuml-diagram#16]
```
extensionService.ts:165 Extension host terminated unexpectedly. Code:  7  Signal:  null
t._onExtensionHostCrashed @ extensionService.ts:165
```
```
extensionHost.ts:236 /Users/cem/.vscode/extensions/jaimeolivares.yuml-3.1.2/node_modules/viz.js/viz.js:25
var Module=typeof Module!=="undefined"?Module:{};var moduleOverrides={};var key;for(key in Module){if(Module.hasOwnProperty(key)){moduleOverrides[key]=Module[key]}}Module["arguments"]=[];Module["thisProgram"]="./this.program";Module["quit"]=(function(status,toThrow){throw toThrow});Module["preRun"]=[];Module["postRun"]=[];var ENVIRONMENT_IS_WEB=false;var ENVIRONMENT_IS_WORKER=false;var ENVIRONMENT_IS_NODE=false;var ENVIRONMENT_IS_SHELL=false;if(Module["ENVIRONMENT"]){if(Module["ENVIRONMENT"]==="WEB"){ENVIRONMENT_IS_WEB=true}else if(Module["ENVIRONMENT"]==="WORKER"){ENVIRONMENT_IS_WORKER=true}else if(Module["ENVIRONMENT"]==="NODE"){ENVIRONMENT_IS_NODE=true}else if(Module["ENVIRONMENT"]==="SHELL"){ENVIRONMENT_IS_SHELL=true}else{throw new Error("Module['ENVIRONMENT'] value is not valid. must be one of: WEB|WORKER|NODE|SHELL.")}}else{ENVIRONMENT_IS_WEB=typeof window==="object";ENVIRONMENT_IS_WORKER=typeof importScripts==="funct

Error: write EPIPE
	at _errnoException (util.js:1024:11)
	at WriteWrap.afterWrite [as oncomplete] (net.js:867:14)
```

**Comment by jaime-olivares** [comment]
Sorry, I will need more context

**Comment by SebastianKristof** [comment]
Yeah I wish I could give you more... it just crashes intermittently. I was viewing a diagram, then I closed the preview window. Then I tried to open preview again by hitting a button in the top right corner, but the preview didn't appear. Closing and reopening the .yuml file did not help. After a few seconds, the error message appeared.

**Comment by jaime-olivares** [comment]
Ok, then this is not the right place. You should report it to https://github.com/jaime-olivares/vscode-yuml/issues specifying your environment.

**Comment by SebastianKristof** [comment]
Done, thanks! https://github.com/jaime-olivares/vscode-yuml/issues/55
